title: "Phil Git Blog"
description: "Un blog personale di Filippo Albertin"
author: "phil"
url: "https://applephil75.github.io"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
