title: "Filippo Albertin"
description: "Notes, essays, culture and the Web."
url: "https://applephil75.github.io"
baseurl: ""

author:
  name: "Filippo Albertin"

markdown: kramdown
permalink: /:year/:month/:day/:title/

theme: null

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
